<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKru7I0W\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKru7I0W/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKru7I0W.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKru7I0W\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKru7I0W\App_KernelDevDebugContainer([
    'container.build_hash' => 'Kru7I0W',
    'container.build_id' => '919c76be',
    'container.build_time' => 1623330686,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKru7I0W');
